### ISSUE TITLE
Error when access the admin panel.

### ISSUE THREAD

**Issue by Rajnikantk** [julienanquetil/M2SendinBlue#1]
Hi, 

I have installed this extension in Magento 2.2 but after installation when I tried to access the admin panel it gives me below error message. Please help. 

1 exception(s):
Exception #0 (Exception): Unable to retrieve Sendinblue Contact List

Exception #0 (Exception): Unable to retrieve Sendinblue Contact List
#0 /home/finnline/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(458): JulienAnquetil\M2SendinBlue\Model\Config\Source\Listes->toOptionArray(false)
#1 /home/finnline/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(376): Magento\Config\Model\Config\Structure\Element\Field->_getOptionsFromSourceModel(Object(JulienAnquetil\M2SendinBlue\Model\Config\Source\Listes))
#2 /home/finnline/public_html/generated/code/Magento/Config/Model/Config/Structure/Element/Field/Interceptor.php(323): Magento\Config\Model\Config\Structure\Element\Field->getOptions()
#3 /home/finnline/public_html/vendor/magento/module-config/Block/System/Config/Form.php(403): Magento\Config\Model\Config\Structure\Element\Field\Interceptor->getOptions()
#4 /home/finnline/public_html/vendor/magento/module-config/Block/System/Config/Form.php(324): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'config/general/...', '', '')
#5 /home/finnline/public_html/vendor/magento/module-config/Block/System/Config/Form.php(264): Magento\Config\Block\System\Config\Form->initFields(Object(Magento\Framework\Data\Form\Element\Fieldset), Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section))
#6 /home/finnline/public_html/vendor/magento/module-config/Block/System/Config/Form.php(210): Magento\Config\Block\System\Config\Form->_initGroup(Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section), Object(Magento\Framework\Data\Form))
#7 /home/finnline/public_html/vendor/magento/module-config/Block/System/Config/Form.php(549): Magento\Config\Block\System\Config\Form->initForm()
#8 /home/finnline/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(666): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#9 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#10 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#11 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#12 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#13 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#14 /home/finnline/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#15 /home/finnline/public_html/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#16 /home/finnline/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/finnline/...')
#17 /home/finnline/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/home/finnline/...', Array)
#18 /home/finnline/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/home/finnline/...')
#19 /home/finnline/public_html/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#20 /home/finnline/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#21 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#22 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#23 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#24 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#25 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', true)
#26 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...')
#27 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#28 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#29 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#30 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#31 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#32 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#33 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#34 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#35 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#36 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#37 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.col')
#38 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#39 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#40 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#41 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#42 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#43 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#44 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#45 /home/finnline/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#46 /home/finnline/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout

**Comment by julienanquetil** [comment]
Hi,

Di you enter you api V2 key in the admin  ?
Thanks

**Comment by Rajnikantk** [comment]
To enter api V2 key, I need to login into the admin but after installing extension, I am not able to access the admin.

- Raj

**Comment by Rajnikantk** [comment]
To enter api V2 key, I need to login into the admin but after installing extension, I am not able to access the admin.

 

- Raj

**Comment by julienanquetil** [comment]
Strange issue cause the error you got "Unable to retrieve Sendinblue Contact List" can appear if api key is entered and can't reach the sendinblue api.
Do you try to clear cache / deploy code (and before remove the generated one) ?
Do you have any entry in your db in core_config_data with path "config/general/api_key" ?

Thanks
